# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dharm Veer
email: d.veer@dal.ca
description: >- # this means to ignore newlines until "baseurl:"
  I am currently a postdoctoral fellow at the Indian Institute of Technology Gandhinagari, India.
  I did my PhD in Mathematics from Chennai Mathematical Insitute, India under the supervision of professor Manoj Kummini.
  My mathematical interests broadly include Commutative Algebra and Combinatorics. 

#Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
  
#  resume_google_scholar_url: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=AIc3KfsAAAAJ" 
  #twitter_username: username
github_username: cmidharm
minimal_mistakes_skin: air
#search: true
google_analytics: cmidharm
  
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

#author:
#  name   : Dharm Veer
#  avatar : "dharm-webpage.jpeg"
  #  bio    : "My awesome biography constrained to a sentence or two goes here."
 # Outputting
 # permalink: /:categories/:title/
  #paginate: 5 # amount of posts to show
  #paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Author
author:
  name             : "Dharm Veer"
  avatar           : "dharm-webpage.jpeg"
  bio              : "AARMS Postdoctoral Fellow"
  location         :
  email            : "d.veer@dal.ca"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : cmidharm
  google:
    scholar        : "AIc3KfsAAAAJ&hl"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :

  # Custom author fields follow
  arxiv            : "veer_d_1"
  google-scholar   : "AIc3KfsAAAAJ&hl"

  resume_google_scholar_url:           "https://scholar.google.com/citations?user=AIc3KfsAAAAJ&hl=en/"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache



links:
#  - label: "Email"
#    icon: "fas fa-fw fa-envelope-square"
      # - label: "Website"
  #  icon: "fas fa-fw fa-link"
  #  url: "https://scholar.google.com/citations?user=AIc3KfsAAAAJ&hl=en"
  - label: "Google Scholar"
    icon: "ai ai-google-scholar"
    url: "https://scholar.google.com/citations?user=AIc3KfsAAAAJ&hl=en/"
  #  - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
  #    url: "https://github.com/"
  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"

      #footer:
      # links:
      # - label: "Twitter"
      #icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
      # - label: "GitHub"
      # icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
      # - label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      #url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
#   _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true    

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
