theme: jekyll-theme-minimal
#theme: Dinky
title: Dharm Veer
description: [Presentations](Presentations)

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

docs:
  - title: Getting Started
    children:
      - title: "Quick-Start Guide"
        #  url: /docs/quick-start-guide/
      - title: "Structure"
        # url: /docs/structure/
      - title: "Installation"
        # url: /docs/installation/
      - title: "Upgrading"
        # url:      
