#theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll
#theme: Dinky
title: Dharm Veer
#description: [Presentations](Presentations)
image: dharm-webpage.jpeg
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
toc: true
toc_label: "My Table of Contents"
toc_icon: "cog"

docs:
  - title: Getting Started
    children:
      - title: "Quick-Start Guide"
        #  url: /docs/quick-start-guide/
      - title: "Structure"
        # url: /docs/structure/
      - title: "Installation"
        # url: /docs/installation/
      - title: "Upgrading"
        # url:      
